print("🌟" * 15)
print("   WELCOME TO BIO CARD MAKER")
print("🌟" * 15)

name = input("\n👤 Your name: ")
age = input("🎂 Your age: ")
college = input("🏫 College: ")
skill = input("💻 Favorite skill: ")
dream = input("🚀 Dream job: ")

print("\n" + "=" * 35)
print("          YOUR BIO CARD")
print("=" * 35)
print(f"✨ Name     : {name}")
print(f"🎉 Age      : {age} years")
print(f"🏫 College  : {college}")
print(f"💻 Skill    : {skill}")
print(f"🚀 Dream    : {dream}")
print("=" * 35)
print("   Keep coding, keep growing! 🌱")
print("=" * 35)
